// <auto-generated />
using System;
using Core.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Core.Migrations
{
    [DbContext(typeof(PlanningDbContext))]
    [Migration("20190612085645_StakeholderRatingAnswersToDictionaries_OnDelete_Restricted_To_Dictionaries")]
    partial class StakeholderRatingAnswersToDictionaries_OnDelete_Restricted_To_Dictionaries
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Core.Entities.BooleanAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Answer");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int?>("CreatedBy");

                    b.Property<int>("QuestionId");

                    b.Property<int?>("ResourceId");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int?>("UpdatedBy");

                    b.Property<int>("UserStepResultId");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("ResourceId");

                    b.HasIndex("UserStepResultId");

                    b.ToTable("BooleanAnswers");
                });

            modelBuilder.Entity("Core.Entities.Dictionary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int?>("CreatedBy");

                    b.Property<bool>("HasPosition")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<bool>("HasStakeholderCategory")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<bool>("HasStakeholderCriteria")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<bool>("HasValue")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int?>("UpdatedBy");

                    b.HasKey("Id");

                    b.ToTable("Dictionaries");
                });

            modelBuilder.Entity("Core.Entities.File", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int?>("CreatedBy");

                    b.Property<string>("Ext")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<int?>("QuestionId");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("Core.Entities.FileAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int?>("CreatedBy");

                    b.Property<int>("FileId");

                    b.Property<int>("QuestionId");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int?>("UpdatedBy");

                    b.Property<int>("UserStepResultId");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserStepResultId");

                    b.ToTable("FileAnswers");
                });

            modelBuilder.Entity("Core.Entities.Introduction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<string>("Step")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int?>("UpdatedBy");

                    b.Property<int>("VideoId");

                    b.HasKey("Id");

                    b.HasIndex("VideoId")
                        .IsUnique();

                    b.ToTable("Introductions");
                });

            modelBuilder.Entity("Core.Entities.IssueOptionAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Actors")
                        .HasMaxLength(1000);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int?>("CreatedBy");

                    b.Property<bool>("IsBestOption")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<int>("IssueId");

                    b.Property<string>("Option")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("QuestionId");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int?>("UpdatedBy");

                    b.Property<int>("UserStepResultId");

                    b.HasKey("Id");

                    b.HasIndex("IssueId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserStepResultId");

                    b.ToTable("IssueOptionAnswers");
                });

            modelBuilder.Entity("Core.Entities.IssueOptionAnswerToResource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IssueOptionAnswerId");

                    b.Property<int>("ResourceId");

                    b.HasKey("Id");

                    b.HasIndex("IssueOptionAnswerId");

                    b.HasIndex("ResourceId");

                    b.ToTable("IssueOptionAnswersToResources");
                });

            modelBuilder.Entity("Core.Entities.Option", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int?>("CreatedBy");

                    b.Property<string>("Description")
                        .HasMaxLength(1000);

                    b.Property<int>("QuestionId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int?>("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Options");
                });

            modelBuilder.Entity("Core.Entities.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int?>("CreatedBy");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<DateTime?>("EndDate");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<bool?>("IsWithActionPlan");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<DateTime>("StartDate");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int?>("UpdatedBy");

                    b.HasKey("Id");

                    b.ToTable("Plans");
                });

            modelBuilder.Entity("Core.Entities.PreparingAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("Date");

                    b.Property<string>("HowItWillBeDone")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<int>("IssueOptionAnswerId");

                    b.Property<int>("QuestionId");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int?>("UpdatedBy");

                    b.Property<int>("UserStepResultId");

                    b.HasKey("Id");

                    b.HasIndex("IssueOptionAnswerId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserStepResultId");

                    b.ToTable("PreparingAnswers");
                });

            modelBuilder.Entity("Core.Entities.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("CanSpecifyOther")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int?>("CreatedBy");

                    b.Property<string>("Description")
                        .HasMaxLength(1000);

                    b.Property<bool>("HasFiles");

                    b.Property<bool>("HasOptions")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<int>("Order");

                    b.Property<int?>("StepBlockId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int?>("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("StepBlockId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("Core.Entities.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int?>("CreatedBy");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("Core.Entities.SWOTAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int?>("CreatedBy");

                    b.Property<bool>("IsIssue");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<int>("QuestionId");

                    b.Property<string>("Type");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int?>("UpdatedBy");

                    b.Property<int>("UserStepResultId");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserStepResultId");

                    b.ToTable("SWOTAnswers");
                });

            modelBuilder.Entity("Core.Entities.SelectAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AltOption")
                        .HasMaxLength(100);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int?>("CreatedBy");

                    b.Property<int?>("IssueId");

                    b.Property<int?>("OptionId");

                    b.Property<int>("QuestionId");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int?>("UpdatedBy");

                    b.Property<int>("UserStepResultId");

                    b.HasKey("Id");

                    b.HasIndex("IssueId");

                    b.HasIndex("OptionId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserStepResultId");

                    b.ToTable("SelectAnswers");
                });

            modelBuilder.Entity("Core.Entities.StakeholderAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CategoryId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int?>("CreatedBy");

                    b.Property<string>("Email")
                        .HasMaxLength(100);

                    b.Property<string>("FirstName")
                        .HasMaxLength(100);

                    b.Property<bool>("IsInternal")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .HasMaxLength(100);

                    b.Property<int>("QuestionId");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int?>("UpdatedBy");

                    b.Property<int?>("UserId");

                    b.Property<int>("UserStepResultId");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserStepResultId");

                    b.ToTable("StakeholderAnswers");
                });

            modelBuilder.Entity("Core.Entities.StakeholderRatingAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int?>("CreatedBy");

                    b.Property<double?>("Grade");

                    b.Property<int>("Priority");

                    b.Property<int>("QuestionId");

                    b.Property<int>("StakeholderId");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int?>("UpdatedBy");

                    b.Property<int>("UserStepResultId");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("StakeholderId");

                    b.HasIndex("UserStepResultId");

                    b.ToTable("StakeholderRatingAnswers");
                });

            modelBuilder.Entity("Core.Entities.StakeholderRatingAnswerToDictionary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CriterionId");

                    b.Property<int>("Rate");

                    b.Property<int>("StakeholderRatingAnswerId");

                    b.HasKey("Id");

                    b.HasIndex("CriterionId");

                    b.HasIndex("StakeholderRatingAnswerId");

                    b.ToTable("StakeholderRatingAnswersToDictionaries");
                });

            modelBuilder.Entity("Core.Entities.StepBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int?>("CreatedBy");

                    b.Property<string>("Description")
                        .HasMaxLength(5000);

                    b.Property<string>("Instruction")
                        .HasMaxLength(5000);

                    b.Property<int>("Order");

                    b.Property<string>("Step")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int?>("UpdatedBy");

                    b.HasKey("Id");

                    b.ToTable("StepBlocks");
                });

            modelBuilder.Entity("Core.Entities.StepResponsible", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int?>("CreatedBy");

                    b.Property<string>("Step")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("UserToPlanId");

                    b.HasKey("Id");

                    b.HasIndex("UserToPlanId");

                    b.ToTable("StepResponsibles");
                });

            modelBuilder.Entity("Core.Entities.StepTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int?>("CreatedBy");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(true);

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<int>("PlanId");

                    b.Property<int?>("Remind");

                    b.Property<DateTime?>("Schedule");

                    b.Property<string>("Step")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int?>("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.ToTable("StepTasks");
                });

            modelBuilder.Entity("Core.Entities.StepTaskAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int?>("CreatedBy");

                    b.Property<string>("Email")
                        .HasMaxLength(100);

                    b.Property<string>("FirstName")
                        .HasMaxLength(100);

                    b.Property<bool>("IsDefinitive")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .HasMaxLength(100);

                    b.Property<int>("StepTaskId");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int?>("UpdatedBy");

                    b.Property<int>("UserStepResultId");

                    b.Property<int?>("UserToPlanId");

                    b.HasKey("Id");

                    b.HasIndex("StepTaskId");

                    b.HasIndex("UserStepResultId");

                    b.HasIndex("UserToPlanId");

                    b.ToTable("StepTaskAnswers");
                });

            modelBuilder.Entity("Core.Entities.StrategicIssueAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int?>("CreatedBy");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<int>("IssueId");

                    b.Property<int>("QuestionId");

                    b.Property<int>("Ranking");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<string>("Solution")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int?>("UpdatedBy");

                    b.Property<int>("UserStepResultId");

                    b.Property<string>("Why")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.HasKey("Id");

                    b.HasIndex("IssueId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserStepResultId");

                    b.ToTable("StrategicIssueAnswers");
                });

            modelBuilder.Entity("Core.Entities.TextAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int?>("CreatedBy");

                    b.Property<int>("QuestionId");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int?>("UpdatedBy");

                    b.Property<int>("UserStepResultId");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserStepResultId");

                    b.ToTable("TextAnswers");
                });

            modelBuilder.Entity("Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int?>("CreatedBy");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.Property<int?>("PositionId");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Token")
                        .HasMaxLength(128);

                    b.Property<DateTime?>("TokenExpiration");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int?>("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("PositionId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Core.Entities.UserStepResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int?>("CreatedBy");

                    b.Property<bool>("IsDefinitive")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<bool?>("IsFinal");

                    b.Property<bool>("IsSubmitted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<int?>("PlanId");

                    b.Property<int?>("QuestionId");

                    b.Property<string>("Step")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int?>("UpdatedBy");

                    b.Property<int?>("UserToPlanId");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserToPlanId");

                    b.ToTable("UserStepResults");
                });

            modelBuilder.Entity("Core.Entities.UserToIssueOptionAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IssueOptionAnswerId");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("IssueOptionAnswerId");

                    b.HasIndex("UserId");

                    b.ToTable("UsersToIssueOptionAnswers");
                });

            modelBuilder.Entity("Core.Entities.UserToPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int?>("CreatedBy");

                    b.Property<int>("PlanId");

                    b.Property<int?>("PositionId");

                    b.Property<string>("Step")
                        .HasMaxLength(100);

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("PositionId");

                    b.HasIndex("UserId");

                    b.ToTable("UsersToPlans");
                });

            modelBuilder.Entity("Core.Entities.ValueAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int?>("CreatedBy");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<int>("QuestionId");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int?>("UpdatedBy");

                    b.Property<int>("UserStepResultId");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserStepResultId");

                    b.ToTable("ValueAnswers");
                });

            modelBuilder.Entity("Core.Entities.BooleanAnswer", b =>
                {
                    b.HasOne("Core.Entities.Question", "Question")
                        .WithMany("BooleanAnswers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Core.Entities.Resource", "Resource")
                        .WithMany("BooleanAnswers")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Core.Entities.UserStepResult", "UserStepResult")
                        .WithMany("BooleanAnswers")
                        .HasForeignKey("UserStepResultId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Core.Entities.File", b =>
                {
                    b.HasOne("Core.Entities.Question", "Question")
                        .WithMany("Files")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Core.Entities.FileAnswer", b =>
                {
                    b.HasOne("Core.Entities.File", "File")
                        .WithMany("FileAnswers")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Core.Entities.Question", "Question")
                        .WithMany("FileAnswers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Core.Entities.UserStepResult", "UserStepResult")
                        .WithMany("FileAnswers")
                        .HasForeignKey("UserStepResultId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Core.Entities.Introduction", b =>
                {
                    b.HasOne("Core.Entities.File", "Video")
                        .WithOne("Introduction")
                        .HasForeignKey("Core.Entities.Introduction", "VideoId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Core.Entities.IssueOptionAnswer", b =>
                {
                    b.HasOne("Core.Entities.SWOTAnswer", "Issue")
                        .WithMany("IssueOptionAnswers")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Core.Entities.Question", "Question")
                        .WithMany("IssueOptionAnswers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Core.Entities.UserStepResult", "UserStepResult")
                        .WithMany("IssueOptionAnswers")
                        .HasForeignKey("UserStepResultId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Core.Entities.IssueOptionAnswerToResource", b =>
                {
                    b.HasOne("Core.Entities.IssueOptionAnswer", "IssueOptionAnswer")
                        .WithMany("IssueOptionAnswersToResources")
                        .HasForeignKey("IssueOptionAnswerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Core.Entities.Resource", "Resource")
                        .WithMany("IssueOptionAnswersToResources")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Core.Entities.Option", b =>
                {
                    b.HasOne("Core.Entities.Question", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Core.Entities.PreparingAnswer", b =>
                {
                    b.HasOne("Core.Entities.IssueOptionAnswer", "IssueOptionAnswer")
                        .WithMany("PreparingAnswers")
                        .HasForeignKey("IssueOptionAnswerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Core.Entities.Question", "Question")
                        .WithMany("PreparingAnswers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Core.Entities.UserStepResult", "UserStepResult")
                        .WithMany("PreparingAnswers")
                        .HasForeignKey("UserStepResultId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Core.Entities.Question", b =>
                {
                    b.HasOne("Core.Entities.StepBlock", "StepBlock")
                        .WithMany("Questions")
                        .HasForeignKey("StepBlockId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Core.Entities.SWOTAnswer", b =>
                {
                    b.HasOne("Core.Entities.Question", "Question")
                        .WithMany("SWOTAnswers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Core.Entities.UserStepResult", "UserStepResult")
                        .WithMany("SWOTAnswers")
                        .HasForeignKey("UserStepResultId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Core.Entities.SelectAnswer", b =>
                {
                    b.HasOne("Core.Entities.SWOTAnswer", "Issue")
                        .WithMany("SelectAnswers")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Core.Entities.Option", "Option")
                        .WithMany("SelectAnswers")
                        .HasForeignKey("OptionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Core.Entities.Question", "Question")
                        .WithMany("SelectAnswers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Core.Entities.UserStepResult", "UserStepResult")
                        .WithMany("SelectAnswers")
                        .HasForeignKey("UserStepResultId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Core.Entities.StakeholderAnswer", b =>
                {
                    b.HasOne("Core.Entities.Dictionary", "Category")
                        .WithMany("CategoryStakeholders")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Core.Entities.Question", "Question")
                        .WithMany("StakeholderAnswers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Core.Entities.User", "User")
                        .WithMany("StakeholderAnswers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Core.Entities.UserStepResult", "UserStepResult")
                        .WithMany("StakeholderAnswers")
                        .HasForeignKey("UserStepResultId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Core.Entities.StakeholderRatingAnswer", b =>
                {
                    b.HasOne("Core.Entities.Question", "Question")
                        .WithMany("StakeholderRatingAnswers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Core.Entities.StakeholderAnswer", "Stakeholder")
                        .WithMany("StakeholderRatingAnswers")
                        .HasForeignKey("StakeholderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Core.Entities.UserStepResult", "UserStepResult")
                        .WithMany("StakeholderRatingAnswers")
                        .HasForeignKey("UserStepResultId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Core.Entities.StakeholderRatingAnswerToDictionary", b =>
                {
                    b.HasOne("Core.Entities.Dictionary", "Criterion")
                        .WithMany("StakeholderRatingAnswersToDictionaries")
                        .HasForeignKey("CriterionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Core.Entities.StakeholderRatingAnswer", "StakeholderRatingAnswer")
                        .WithMany("Criteria")
                        .HasForeignKey("StakeholderRatingAnswerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Core.Entities.StepResponsible", b =>
                {
                    b.HasOne("Core.Entities.UserToPlan", "UserToPlan")
                        .WithMany("StepResponsibles")
                        .HasForeignKey("UserToPlanId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Core.Entities.StepTask", b =>
                {
                    b.HasOne("Core.Entities.Plan", "Plan")
                        .WithMany("StepTasks")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Core.Entities.StepTaskAnswer", b =>
                {
                    b.HasOne("Core.Entities.StepTask", "StepTask")
                        .WithMany("StepTaskAnswers")
                        .HasForeignKey("StepTaskId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Core.Entities.UserStepResult", "UserStepResult")
                        .WithMany("StepTaskAnswers")
                        .HasForeignKey("UserStepResultId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Core.Entities.UserToPlan", "UserToPlan")
                        .WithMany("StepTaskAnswers")
                        .HasForeignKey("UserToPlanId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Core.Entities.StrategicIssueAnswer", b =>
                {
                    b.HasOne("Core.Entities.SWOTAnswer", "Issue")
                        .WithMany("StrategicIssueAnswers")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Core.Entities.Question", "Question")
                        .WithMany("StrategicIssueAnswers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Core.Entities.UserStepResult", "UserStepResult")
                        .WithMany("StrategicIssueAnswers")
                        .HasForeignKey("UserStepResultId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Core.Entities.TextAnswer", b =>
                {
                    b.HasOne("Core.Entities.Question", "Question")
                        .WithMany("TextAnswers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Core.Entities.UserStepResult", "UserStepResult")
                        .WithMany("TextAnswers")
                        .HasForeignKey("UserStepResultId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Core.Entities.User", b =>
                {
                    b.HasOne("Core.Entities.Dictionary", "Position")
                        .WithMany("Users")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Core.Entities.UserStepResult", b =>
                {
                    b.HasOne("Core.Entities.Plan", "Plan")
                        .WithMany("AdminStepResults")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Core.Entities.Question")
                        .WithMany("UserStepResults")
                        .HasForeignKey("QuestionId");

                    b.HasOne("Core.Entities.UserToPlan", "UserToPlan")
                        .WithMany("UserStepResults")
                        .HasForeignKey("UserToPlanId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Core.Entities.UserToIssueOptionAnswer", b =>
                {
                    b.HasOne("Core.Entities.IssueOptionAnswer", "IssueOptionAnswer")
                        .WithMany("UsersToIssueOptionAnswers")
                        .HasForeignKey("IssueOptionAnswerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Core.Entities.User", "User")
                        .WithMany("UsersToIssueOptionAnswers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Core.Entities.UserToPlan", b =>
                {
                    b.HasOne("Core.Entities.Plan", "Plan")
                        .WithMany("UsersToPlans")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Core.Entities.Dictionary", "Position")
                        .WithMany("UsersToPlans")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Core.Entities.User", "User")
                        .WithMany("UsersToPlans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Core.Entities.ValueAnswer", b =>
                {
                    b.HasOne("Core.Entities.Question", "Question")
                        .WithMany("ValueAnswers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Core.Entities.UserStepResult", "UserStepResult")
                        .WithMany("ValueAnswers")
                        .HasForeignKey("UserStepResultId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
