//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class steps {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal steps() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.steps", typeof(steps).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Making a detailed action plan.
        /// </summary>
        public static string ActionPlanDetailed {
            get {
                return ResourceManager.GetString("ActionPlanDetailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key questions for the action plan.
        /// </summary>
        public static string ActionPlanKeyQuestions {
            get {
                return ResourceManager.GetString("ActionPlanKeyQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation.
        /// </summary>
        public static string Evalution {
            get {
                return ResourceManager.GetString("Evalution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operational and strategic issues.
        /// </summary>
        public static string IssuesDistinguish {
            get {
                return ResourceManager.GetString("IssuesDistinguish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mission Statement.
        /// </summary>
        public static string Mission {
            get {
                return ResourceManager.GetString("Mission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-Departure Checklist.
        /// </summary>
        public static string Predeparture {
            get {
                return ResourceManager.GetString("Predeparture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviewing strategies &amp;amp; implementation plans.
        /// </summary>
        public static string Review {
            get {
                return ResourceManager.GetString("Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stakeholder Analysis.
        /// </summary>
        public static string StakeholdersAnalysis {
            get {
                return ResourceManager.GetString("StakeholdersAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifying the Party&apos;s Stakeholders.
        /// </summary>
        public static string StakeholdersIdentify {
            get {
                return ResourceManager.GetString("StakeholdersIdentify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master List of key strategis issues.
        /// </summary>
        public static string StrategicIssues {
            get {
                return ResourceManager.GetString("StrategicIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SWOT.
        /// </summary>
        public static string SWOT {
            get {
                return ResourceManager.GetString("SWOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values Statement.
        /// </summary>
        public static string Values {
            get {
                return ResourceManager.GetString("Values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sketching a Vision.
        /// </summary>
        public static string Vision {
            get {
                return ResourceManager.GetString("Vision", resourceCulture);
            }
        }
    }
}
